// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rasyonet_Intern.API.Data;

#nullable disable

namespace Rasyonet_Intern.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rasyonet_Intern.API.Models.FonKategori", b =>
                {
                    b.Property<int>("FonKategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FonKategoriId"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FonKategoriId");

                    b.ToTable("fonKategoriler");
                });

            modelBuilder.Entity("Rasyonet_Intern.API.Models.FonPerformans", b =>
                {
                    b.Property<int>("FonPerformansId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FonPerformansId"));

                    b.Property<decimal>("AylikDegisimYuzde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Buyukluk")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FonAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FonKategoriId")
                        .HasColumnType("int");

                    b.Property<string>("FonKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GunlukDegisimYuzde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HaftalikDegisimYuzde")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FonPerformansId");

                    b.HasIndex("FonKategoriId");

                    b.ToTable("fonPerformanslar");
                });

            modelBuilder.Entity("Rasyonet_Intern.API.Models.FonPerformans", b =>
                {
                    b.HasOne("Rasyonet_Intern.API.Models.FonKategori", "FonKategori")
                        .WithMany("FonPerformanslar")
                        .HasForeignKey("FonKategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FonKategori");
                });

            modelBuilder.Entity("Rasyonet_Intern.API.Models.FonKategori", b =>
                {
                    b.Navigation("FonPerformanslar");
                });
#pragma warning restore 612, 618
        }
    }
}
